-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 16:28:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sw-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sw-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sw-project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sw-project` ;

-- -----------------------------------------------------
-- Table `sw-project`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`person` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NULL DEFAULT NULL COMMENT 'neu',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '-',
  `google_user_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '-',
  `google_mail` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '-',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`learngroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`learngroup` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NULL DEFAULT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_learngroup_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_learngroup_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `sw-project`.`person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`chat` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `is_accepted` TINYINT NOT NULL,
  `learngroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_learngroup1_idx` (`learngroup_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_learngroup1`
    FOREIGN KEY (`learngroup_id`)
    REFERENCES `sw-project`.`learngroup` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`chatmessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`chatmessage` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `text` VARCHAR(10000) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `chat_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatmessage_chat1_idx` (`chat_id` ASC) VISIBLE,
  INDEX `fk_chatmessage_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatmessage_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `sw-project`.`chat` (`id`),
  CONSTRAINT `fk_chatmessage_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `sw-project`.`person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`learnprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`learnprofile` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NULL DEFAULT NULL,
  `study_status` TINYINT NOT NULL DEFAULT '0',
  `frequency` INT NOT NULL,
  `prev_knowledge` VARCHAR(10000) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `group_size` INT NOT NULL DEFAULT '0',
  `extroversion` TINYINT NOT NULL DEFAULT '0',
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_learnprofile_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_learnprofile_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `sw-project`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`grouprequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`grouprequest` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `is_accepted` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `learngroup_id` INT NOT NULL,
  `learnprofile_id` INT NOT NULL,
  INDEX `fk_grouprequest_learngroup1_idx` (`learngroup_id` ASC) VISIBLE,
  INDEX `fk_grouprequest_learnprofile1_idx` (`learnprofile_id` ASC) VISIBLE,
  CONSTRAINT `fk_grouprequest_learngroup1`
    FOREIGN KEY (`learngroup_id`)
    REFERENCES `sw-project`.`learngroup` (`id`),
  CONSTRAINT `fk_grouprequest_learnprofile1`
    FOREIGN KEY (`learnprofile_id`)
    REFERENCES `sw-project`.`learnprofile` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sw-project`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sw-project`.`profile` (
  `id` INT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `age` INT NOT NULL,
  `adress` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '-',
  `semester` INT NOT NULL,
  `degree_course` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `sw-project`.`person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
